<#
.SYNOPSIS
    Register docvault context-menu verbs in HKCU (no admin required).

.DESCRIPTION
    Adds three right-click verbs to all files:
      "Ingest into docvault"             -> docvault-ingest.bat "%1"
      "Ingest into docvault (AI)"        -> docvault-ingest-ai.bat "%1"
      "Ingest document in-place (AI)"    -> docvault-ingest-inplace.bat "%1"
    Plus one right-click verb on folders:
      "Ingest folder into docvault"      -> docvault-ingest-folder.bat "%1"

    Run uninstall-context-menu.ps1 to remove.

    Per-user install -- writes only under HKCU\Software\Classes\.
    No admin elevation required, but you may need to restart Explorer
    before it picks up the new verbs:
        Stop-Process -Name explorer -Force
#>

$ErrorActionPreference = 'Stop'

$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$ingestBat        = Join-Path $here 'docvault-ingest.bat'
$ingestAiBat      = Join-Path $here 'docvault-ingest-ai.bat'
$ingestInplaceBat = Join-Path $here 'docvault-ingest-inplace.bat'
$ingestFolderBat  = Join-Path $here 'docvault-ingest-folder.bat'
$hiddenLauncher   = Join-Path $here 'launch-hidden.vbs'
$iconFile         = Join-Path $here 'docvault.ico'

if (-not (Test-Path -LiteralPath $ingestBat))        { throw "missing $ingestBat" }
if (-not (Test-Path -LiteralPath $ingestAiBat))      { throw "missing $ingestAiBat" }
if (-not (Test-Path -LiteralPath $ingestInplaceBat)) { throw "missing $ingestInplaceBat" }
if (-not (Test-Path -LiteralPath $ingestFolderBat))  { throw "missing $ingestFolderBat" }
if (-not (Test-Path -LiteralPath $hiddenLauncher))   { throw "missing $hiddenLauncher" }
# docvault.ico is generated by windows\make-icon.py and committed to the
# repo. If a user has stripped it out, fall back silently to the .bat icon
# (which is the boring default white sheet) rather than failing the install.
if (-not (Test-Path -LiteralPath $iconFile)) { $iconFile = $null }

# We use reg.exe rather than the PowerShell registry provider because the
# path "HKCU\Software\Classes\*\shell\..." contains a literal '*' that
# PowerShell's path engine interprets as a wildcard -- New-Item and
# Set-ItemProperty then try to enumerate every key under Classes\ and hang
# (or fail silently) on a populated registry. reg.exe takes paths as raw
# strings and is bundled with Windows.
function Install-Verb {
    param(
        [string]$VerbKey,
        [string]$DisplayName,
        [string]$BatPath,
        [string]$IconPath = $null,
        [string]$ClassRoot = 'HKCU\Software\Classes\*\shell'   # files by default
    )
    $base = "$ClassRoot\$VerbKey"
    $cmd  = "$base\command"

    # We want this stored as REG_SZ in the registry:
    #   wscript "C:\path\launch-hidden.vbs" "C:\path\to.bat" "%1"
    # so that:
    #   - the cmd window stays hidden (wscript is GUI-subsystem, the .vbs
    #     spawns the .bat with WindowStyle=0)
    #   - filenames containing spaces, '&', '(' etc. survive cmd's tokenizer
    # Getting reg.exe to receive the embedded double-quotes intact is fiddly
    # because PowerShell's native-command argument passer strips them.
    # Workaround: write a temporary .reg file and import it -- the file
    # format takes the value verbatim with \" escapes for inner quotes, and
    # bypasses PowerShell's tokenizer entirely.
    $regBat = $BatPath -replace '\\', '\\'                  # escape backslashes for .reg syntax
    $regVbs = $hiddenLauncher -replace '\\', '\\'
    $verbDisplay = $DisplayName -replace '"', '\"'
    # produces: wscript "C:\path\launch-hidden.vbs" "C:\path\to.bat" "%1"
    $cmdValue = 'wscript \"' + $regVbs + '\" \"' + $regBat + '\" \"%1\"'
    # Use the dedicated .ico when present so Explorer shows a colourful
    # tile instead of the bland white-page icon associated with .bat files.
    $iconValue = if ($IconPath) { $IconPath -replace '\\', '\\' } else { $regBat }

    $regBaseKey = $base -replace '^HKCU', 'HKEY_CURRENT_USER'
    $regCmdKey  = $cmd  -replace '^HKCU', 'HKEY_CURRENT_USER'

    $regBody = @"
Windows Registry Editor Version 5.00

[$regBaseKey]
@="$verbDisplay"
"Icon"="$iconValue"

[$regCmdKey]
@="$cmdValue"
"@

    $tmp = [System.IO.Path]::ChangeExtension([System.IO.Path]::GetTempFileName(), '.reg')
    # .reg files MUST be UTF-16 LE with BOM for the "Windows Registry Editor
    # Version 5.00" header to be recognized; otherwise reg.exe import errors.
    [System.IO.File]::WriteAllText($tmp, $regBody, [System.Text.UnicodeEncoding]::new($false, $true))
    try {
        # reg.exe writes "The operation completed successfully." to stderr
        # even on success. Don't redirect stderr (2>&1 would trip
        # NativeCommandError under $ErrorActionPreference='Stop'); rely on
        # $LASTEXITCODE alone, and just suppress stdout.
        & reg.exe import $tmp | Out-Null
        if ($LASTEXITCODE -ne 0) { throw "reg.exe import failed for $VerbKey (exit $LASTEXITCODE)" }
    } finally {
        Remove-Item -LiteralPath $tmp -ErrorAction SilentlyContinue
    }
    Write-Host "installed: $DisplayName -> $BatPath"
}

# File verbs (HKCU\Software\Classes\*\shell -- applies to all file types)
Install-Verb -VerbKey 'Docvault'        -DisplayName 'Ingest into docvault'           -BatPath $ingestBat        -IconPath $iconFile
Install-Verb -VerbKey 'DocvaultAI'      -DisplayName 'Ingest into docvault (AI)'      -BatPath $ingestAiBat      -IconPath $iconFile
Install-Verb -VerbKey 'DocvaultInPlace' -DisplayName 'Ingest document in-place (AI)'  -BatPath $ingestInplaceBat -IconPath $iconFile

# Folder verb (HKCU\Software\Classes\Directory\shell -- right-click on folder
# in Explorer's tree or list view).
Install-Verb -VerbKey 'DocvaultFolder' -DisplayName 'Ingest folder into docvault' `
    -BatPath $ingestFolderBat -IconPath $iconFile -ClassRoot 'HKCU\Software\Classes\Directory\shell'

Write-Host ""
Write-Host "Restart Explorer to refresh the context menu:"
Write-Host "  Stop-Process -Name explorer -Force; Start-Process explorer"
